### ISSUE TITLE
add a link to this repo visible on the website

### ISSUE THREAD

**Issue by rhwy** [codingdojo-org/codingdojo.org#3]
people should easily see how and where the content can be updated

**Comment by tclavier** [comment]
Partially done with "edit" button at end of single.html template

**Comment by tclavier** [comment]
Not totally close, we have a bug with little screen.
![tmp_5259-screenshot_20170209-2300451976060422](https://cloud.githubusercontent.com/assets/357257/22805315/2b129f7e-ef1d-11e6-8840-0132e4bc8b4e.png)

**Comment by rhwy** [comment]
it was not only because of the ribbon, it was a generic overflow pb on mobiles when content was bigger than screen. it was not a pb of screen size but a mobile browser rendering pb ;-). 

I fixed the ribbon, the general overflow behavior and the header to fit better on mobile phones.
