### ISSUE TITLE
Translate website into pt_BR (Brazilian Portuguese)

### ISSUE THREAD

**Issue by rogeriopradoj** [codingdojo-org/codingdojo.org#36]
Hello,

Do you think it would be possible to have a version of codingdojo.org translated into pt_BR? 

My ideia, if ok for you, would be having original in http://codingdojo.org and pt_BR version in http://br.codingdojo.org or http://codingdojo.org/pt-br .

As an example, we just did that in https://phptestfest.org/ and https://phptestfest.org/pt-br (https://github.com/phpcommunity/phptestfest.org/tree/master/docs).

Best

**Comment by tclavier** [comment]
IMHO, we can use the hugo multilingual mode : https://gohugo.io/content-management/multilingual/ and start to translate only one page.

**Comment by rogeriopradoj** [comment]
It would be great! Let me know how we could help on that.

Best,

**Comment by tclavier** [comment]
To translate pages you can : 
copy one page like `content/kata/LeapYear.md` in page with lang like `content/kata/LeapYear.pt.md` and translate.
