### ISSUE TITLE
Cannot set up environment (OSX 10.13.2)

### ISSUE THREAD

**Issue by dvrensk** [codingdojo-org/codingdojo.org#44]
I guess this is more of a meta-issue, but I don't know where I should take it.  I want to submit a couple of PRs, but I want to make sure that I've done things right before submitting them, and I cannot replicate the environment.  I've tried it three ways:

## 1. Following instructions

Cloning works fine.  I can also start `hugo server -w` and go to the start page, but any link I click on that page gives a 404 (for instance "What Is Coding Dojo" leads to http://localhost:1313/WhatIsCodingDojo which only says `404 page not found`).

## 2. Generating the static site

Checking the `Dockerfile` I learn that the site can be generated statically using `hugo --destination=/tmp/www`.  Running that gives me the following output

```
$ hugo --destination=/tmp/www

                   | EN   
+------------------+-----+
  Pages            | 217  
  Paginator pages  |   0  
  Non-page files   |   0  
  Static files     |   1  
  Processed images |   0  
  Aliases          |   2  
  Sitemaps         |   1  
  Cleaned          |   0  

Total in 123 ms
```

but looking in `/tmp/www` I see a lot less than 217 files:

```
$ tree /tmp/www
/tmp/www
├── categories
│   ├── index.html
│   └── index.xml
├── css
│   └── codingdojo.css
├── greetings
│   └── index.html
├── home
│   └── index.html
├── index.html
├── index.xml
├── sitemap.xml
└── tags
    ├── index.html
    └── index.xml

5 directories, 10 files
```

## 3. Using Docker

Assuming that something is wrong with my `hugo` installation, I install a modern Docker (I haven't used it for two years) and run it. After many iterations, changing `config.toml` and `nginx_vhost.conf` a bit, I have something I can use:

```$ git diff
diff --git i/config.toml w/config.toml
index 2262eb9..7f95455 100644
--- i/config.toml
+++ w/config.toml
@@ -3,5 +3,5 @@ baseurl = "http://codingdojo.org/"
 title = "Coding Dojo"
 theme = "template-hugo-codingdojo"
 metadataformat = "yaml"
-canonifyurls = true
+canonifyurls = false
 disablePathToLower = true
diff --git i/nginx_vhost.conf w/nginx_vhost.conf
index 6fb91bb..172c73b 100644
--- i/nginx_vhost.conf
+++ w/nginx_vhost.conf
@@ -1,7 +1,8 @@
 server {
   root /var/www;
   index index.html index.htm;
-  server_name localhost codingdojo.org www.codingdojo.org;
+  listen 1080;
+  server_name local.codingdojo.org localhost codingdojo.org www.codingdojo.org;
 
   if (!-f $request_filename) {
     rewrite ^/cgi-bin/index.pl /$args? permanent;
```

Building and running the VM:

```
$ docker build .
Sending build context to Docker daemon   2.16MB
[...]
Step 5/6 : run cd /site && /usr/bin/hugo --destination=/var/www
 ---> Running in 038871fcdd6e
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
211 regular pages created
16 other pages created
0 non-page files copied
0 paginator pages created
0 tags created
0 categories created
total in 674 ms
Removing intermediate container 038871fcdd6e
 ---> 6b2adb5460e3
Step 6/6 : add nginx_vhost.conf /etc/nginx/conf.d/codingdojo.conf
 ---> 9b83de072f94
Successfully built 9b83de072f94

$ docker run  -p 1080:1080 -rm -d 9b83de072f94
...
```

After adding `127.0.0.1 local.codingdojo.org` to `/etc/hosts` I can see all the content at port 1080.  Yay!

## Findings

I think the problem is that `hugo` has moved on in an incompatible manner.  The container runs version 0.26:

```
# hugo version
Hugo Static Site Generator v0.26 linux/amd64 BuildDate: 2017-11-13T18:45:19Z
```

but homebrew installed 0.34 on my Mac.  The Hugo docs talk about putting all content in folders, but that's not how this repo is laid out.

Again, I'm sorry to use this as a support forum, and I'll be happy to use any knowledge gained to improve the README or start building the wiki.

## Ideas

**Option 1:** I'm thinking of picking up some Docker skills and create another VM that will run `hugo server -w` rather than using nginx.  Hopefully I can do it without touching any of the existing files.
**Option 2:** Migrating the repo to current Hugo standards (if that is indeed what's wrong).  It might mean losing the wiki-like naming/structure (but of course there have to be aliases to maintain all old links).

Has anyone tried this?  Does anyone have preferences?  And who calls the shots?

**Comment by tclavier** [comment]
Coding dojo use now the last hugo version
