### ISSUE TITLE
Availability via HTTPS

### ISSUE THREAD

**Issue by szpak** [codingdojo-org/codingdojo.org#49]
It would be nice to have codingdojo.org available via HTTPS. I don't know where the page is hosted, but having Nginx mentioned in the configuration files suggests that https://letsencrypt.org/ could be an option.

**Comment by tclavier** [comment]
Very good idea

**Comment by tclavier** [comment]
Done : https://codingdojo.org/

**Comment by szpak** [comment]
Thanks!

Btw, I've noticed that https://codingdojo.org/pt/ (and fr) displays nothing. However, I don't know how the content looked like before the recent change.

**Comment by tclavier** [comment]
Fench version is not empty ... only one page translated : https://codingdojo.org/fr/kata/FizzBuzz/
