### ISSUE TITLE
Better instructions for adding a dojo

### ISSUE THREAD

**Issue by KGraceNihon** [codingdojo-org/codingdojo.org#59]
Sorry, can't understand your instructions at all. Please add our dojo (I just coped and pasted someone else's raw file):

---
title: "AustinSWCDojo"
draft: false
date: "2018-12-07T11:00:00"
aliases:
  - "/AustinSWCDojo"

---
    The Austin Software Craftsmanship Meetup holds a Coding 
Dojo once a quarter (next dojo Jan 2019). We use 
[\[Cyber-Dojo\]](http://cyber-dojo.org) as a platform in order to support 
multiple languages and test frameworks. Join us 
on [\[Meetup\]](https://www.meetup.com/austin-software-craftsmanship/) for more info.

Our dojo is run "Glasgow style," with pairs working together 
on their own laptops, all on the same kata but not necessarily
all on the same language. Open to all experience levels; 
if you're interested in improving your craft, we want you!

**Comment by tclavier** [comment]
I will add tour dojo. 

Could you give me an URL to the not clear instructions ?

**Comment by KGraceNihon** [comment]
Thank you!

https://github.com/codingdojo-org/codingdojo.org#readme

If all that’s needed to add a dojo is to edit a short text template (as I did), why not just provide the text template? I really don’t want to go find the Hugo website, figure out which binary to download, etc. etc. just to produce a three-paragraph block of text. Your readme could look something like this instead:

“Edit the following template with your information, and submit a pull request….”

Perhaps I am misunderstanding and the more complicated process is really necessary, but I don’t know…

In any case, thank you for providing the site, I’m glad you will list our dojo for us.

Best regards, --Kathy

**Comment by tclavier** [comment]
You can see you Dojo page at : http://codingdojo.org/dojo/AustinSWC/ 
And i have updated the contribution doc, thanks for your feedback.
