### ISSUE TITLE
Cool URI dont change

### ISSUE THREAD

**Issue by yaf** [codingdojo-org/codingdojo.org#7]
Cool URI don't change, but sometimes it's happen. Use [301](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.2) return code, and redirection.

Exemple : 
http://www.codingdojo.org/cgi-bin/index.pl?KataRomanNumerals
->
http://codingdojo.org/kata/RomanNumerals/

**Comment by tclavier** [comment]
Fixed in commit f846930b66e4531bf247b771b7efdb20e0898d84
