### ISSUE TITLE
activate https ?

### ISSUE THREAD

**Issue by etienneCharignon** [codingdojo-org/codingdojo.org#72]
why is codingdojo.org not in https ?

**Comment by Alexis-benoist** [comment]
Good question !

@tclavier, what happened on https://github.com/codingdojo-org/codingdojo.org/commit/7add8f78d8c0767d5a99f3370272778c305f186b ?

**Comment by tclavier** [comment]
It's done

**Comment by tclavier** [comment]
> Good question !
> 
> @tclavier, what happened on [7add8f7](https://github.com/codingdojo-org/codingdojo.org/commit/7add8f78d8c0767d5a99f3370272778c305f186b) ?

An error in Deliverous file trigger letsencrypt limit ... this commit was just to wait the reset of counter ... 2 years later i thinks it's the good time :-)
